# The Bot's Token
token: NTQwODYwOTI1MzY4OTkxNzQ1.DztWPg.2nZG5nMM0-zH0xGwfQs62MBwyWI

# The Bot's Client ID
# client_id: insert_clientid

# Your ID (Optional, for owner commands)
# owner_id: insert_ownerid